"""XBRL Serializer: converts a tagged document into a real XBRL instance XML
document (xbrli:xbrl), instead of the JSON intermediate TaxonomyTagger writes.

Scoped to a PoC: targets the bespoke, non-standard taxonomy in
taxonomy/construction_payment_taxonomy.json, not a published XBRL taxonomy
standard. The schemaRef below resolves to a real generated .xsd (see
taxonomy/generate_taxonomy_artifacts.py), but the output has not been run
through Arelle or any other XBRL processor, so treat it as well-formed and
correctly shaped rather than certified conformant. No multi-context/dimensions/
footnotes support -- one shared context and unit are enough for 4 concepts.
"""

from __future__ import annotations

import json
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional

from taxonomy_tagger import TaggedDocument, TaggedFact

NS = {
    "xbrli": "http://www.xbrl.org/2003/instance",
    "link": "http://www.xbrl.org/2003/linkbase",
    "xlink": "http://www.w3.org/1999/xlink",
    "iso4217": "http://www.xbrl.org/2003/iso4217",
    "cpat": "http://example.org/xbrl/construction-payment-application",
}
for _prefix, _uri in NS.items():
    ET.register_namespace(_prefix, _uri)

# Relative to runs/xbrl/<file>.xml, where instance documents are written --
# generated by taxonomy/generate_taxonomy_artifacts.py.
SCHEMA_REF = "../../taxonomy/construction_payment_taxonomy.xsd"
CONTEXT_ID = "D-1"
UNIT_ID = "USD"
DATE_CONCEPT_FOR_PERIOD = "ApplicationForPaymentDate"


def _qname(prefix: str, tag: str) -> str:
    return f"{{{NS[prefix]}}}{tag}"


class XBRLSerializer:
    def __init__(self, taxonomy_path: Path):
        taxonomy = json.loads(Path(taxonomy_path).read_text(encoding="utf-8"))
        self.concepts: Dict[str, Any] = taxonomy.get("concepts", {})

    def _concept_type(self, concept_id: str) -> Optional[str]:
        return self.concepts.get(concept_id, {}).get("type")

    def _period_instant(self, tagged: TaggedDocument) -> str:
        for fact in tagged.facts:
            if fact.concept == DATE_CONCEPT_FOR_PERIOD and fact.value:
                return str(fact.value)
        return datetime.now(timezone.utc).date().isoformat()

    def serialize(self, tagged: TaggedDocument) -> ET.Element:
        root = ET.Element(_qname("xbrli", "xbrl"))
        # ET.register_namespace only declares a prefix when it's used on an
        # element/attribute name -- iso4217:USD is written as measure *text*,
        # so the prefix must be declared explicitly or it's an unresolvable
        # QName per the XBRL/xmlschema spec (caught by Arelle validation).
        root.set("xmlns:iso4217", NS["iso4217"])

        schema_ref = ET.SubElement(root, _qname("link", "schemaRef"))
        schema_ref.set(_qname("xlink", "type"), "simple")
        schema_ref.set(_qname("xlink", "href"), SCHEMA_REF)

        context = ET.SubElement(root, _qname("xbrli", "context"))
        context.set("id", CONTEXT_ID)
        entity = ET.SubElement(context, _qname("xbrli", "entity"))
        identifier = ET.SubElement(entity, _qname("xbrli", "identifier"))
        identifier.set("scheme", "http://example.org/entity")  # PoC placeholder, not a real EIN/CIK
        identifier.text = tagged.source_document
        period = ET.SubElement(context, _qname("xbrli", "period"))
        instant = ET.SubElement(period, _qname("xbrli", "instant"))
        instant.text = self._period_instant(tagged)

        has_monetary = any(self._concept_type(f.concept) == "monetary" for f in tagged.facts)
        if has_monetary:
            unit = ET.SubElement(root, _qname("xbrli", "unit"))
            unit.set("id", UNIT_ID)
            measure = ET.SubElement(unit, _qname("xbrli", "measure"))
            measure.text = "iso4217:USD"

        for fact in tagged.facts:
            if fact.value is None:
                continue
            concept_type = self._concept_type(fact.concept)
            if concept_type == "group":
                continue

            elem = ET.SubElement(root, _qname("cpat", fact.concept))
            elem.set("contextRef", CONTEXT_ID)
            if concept_type == "monetary":
                elem.set("unitRef", UNIT_ID)
                elem.set("decimals", "2")
            elem.text = str(fact.value)

        return root

    def write(self, tagged: TaggedDocument, out_path: Path) -> Path:
        root = self.serialize(tagged)
        ET.ElementTree(root).write(out_path, xml_declaration=True, encoding="UTF-8")
        return out_path
